services:
  db:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8083:8080'
